<table border="0" style="background:#eee; color:#333; border:solid 1px #000000;">
  <tr>
    <td colspan="2"><strong>Заголовок в теле письма</strong></td>
  </tr>
  <tr>
    <td>%%companytype.title%%</td>
    <td>%%companytype.value%%</td>
  </tr>
  <tr>
    <td>%%name.title%%</td>
    <td>%%name.value%%</td>
  </tr>
  <tr>
    <td>%%tell.title%%</td>
    <td>%%tell.value%%</td>
  </tr>
  <tr>
    <td>%%e-mail.title%%</td>
    <td>%%e-mail.value%%</td>
  </tr>
  <tr>
    <td>%%inn.title%%</td>
    <td>%%inn.value%%</td>
  </tr>
  <tr>
    <td>%%ogrn.title%%</td>
    <td>%%ogrn.value%%</td>
  </tr>
  <tr>
    <td>%%city.title%%</td>
    <td>%%city.value%%</td>
  </tr>
  <tr>
    <td>%%text.title%%</td>
    <td>%%text.value%%</td>
  </tr>
  <tr>
    <td>%%checkbox.title%%</td>
    <td>%%checkbox.value%%</td>
  </tr>
</table>
