<table cellpadding="0" cellspacing="0" border="0" width="100%">
	<tbody>
		<tr valign="top" class="inz3">
			<td width="50%">
				<div id="list">
				    <div><span class="inz1" style="background-color: #9d1f9d;"><input type="Radio" class="inz2" value="м. Беговая" name="adress" id="adr19"></span> <label for="adr19"><a href="javascript:;" onclick="window.open('/contacts/19.html')"><strong>м. Беговая</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 585-81-62</label></div>
					<div><span class="inz1" style="background-color: #9d1f9d;"><input type="Radio" class="inz2" value="м. Октябрьское поле" name="adress" id="adr12"></span> <label for="adr12"><a href="javascript:;" onclick="window.open('/contacts/12.html')"><strong>м. Октябрьское поле</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 664-38-81</label></div>
					<div><span class="inz1" style="background-color: #9d1f9d;"><input type="Radio" class="inz2" value="м. Таганская, м. Марксисткая" name="adress" id="adr13"></span> <label for="adr13"><a href="javascript:;" onclick="window.open('/contacts/13.html')"><strong>м. Таганская, м. Марксисткая</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 506-22-77</label></div>
					<!--<div><span class="inz1" style="background-color: #9d1f9d;"><input type="Radio" class="inz2" value="м. Щукинская" name="adress" id="adr42"></span> <label for="adr42"><a href="javascript:;" onclick="window.open('/contacts/42.html')"><strong>м. Щукинская</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 585-81-62</label></div>-->
				   <!-- <div><span class="inz1" style="background-color: #8dcf3a;"><input type="Radio" class="inz2" value="м. Братиславская" name="adress" id="adr6"></span> <label for="adr6"><a href="javascript:;" onclick="window.open('/contacts/6.html')"><strong>м. Братиславская</strong></a><br><strong style="font-size: 11pt;">(499)</strong> 501-61-97</label></div> -->
					<div><span class="inz1" style="background-color: #008000;"><input type="Radio" class="inz2" value="м. Водный стадион" name="adress" id="adr2"></span> <label for="adr2"><a href="javascript:;" onclick="window.open('/contacts/2.html')"><strong>м. Водный стадион</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 979-88-73</label></div>
					<div><span class="inz1" style="background-color: #008000;"><input type="Radio" class="inz2" value="м. Динамо" name="adress" id="adr41"></span> <label for="adr41"><a href="javascript:;" onclick="window.open('/contacts/41.html')"><strong>м. Динамо</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 532-70-49</label></div>
					<!-- <div><span class="inz1" style="background-color: #008000;"><input type="Radio" class="inz2" value="м. Домодедовская" name="adress" id="adr28"></span> <label for="adr28"><a href="javascript:;" onclick="window.open('/contacts/28.html')"><strong>м. Домодедовская</strong></a><br><strong style="font-size: 11pt;">(925)</strong> 230-57-19</label></div>-->
					<div><span class="inz1" style="background-color: #008000;"><input type="Radio" class="inz2" value="м. Каширская" name="adress" id="adr4"></span> <label for="adr4"><a href="javascript:;" onclick="window.open('/contacts/4.html')"><strong>м. Каширская</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 728-45-98</label></div> 
				   <div><span class="inz1" style="background-color: #8dcf3a;"><input type="Radio" class="inz2" value="м. Братиславская" name="adress" id="adr6"></span> <label for="adr6"><a href="javascript:;" onclick="window.open('/contacts/6.html')"><strong>м. Марьино</strong></a><br><strong style="font-size: 11pt;">(925)</strong>498-20-48</label></div>
				   <!--<div><span class="inz1" style="background-color: #8dcf3a;"><input type="Radio" class="inz2" value="м. Братиславская" name="adress" id="adr6"></span> <label for="adr6"><a href="javascript:;" onclick="window.open('/contacts/6.html')"><strong>м. Братиславская</strong></a><br><strong style="font-size: 11pt;">(925)</strong>498-20-48</label></div>-->
				   <!--<div><span class="inz1" style="background-color: #8dcf3a;"><input type="Radio" class="inz2" value="м. Марьина роща" name="adress" id="adr46"></span> <label for="adr46"><a href="javascript:;" onclick="window.open('/contacts/46.html')"><strong>м. Марьина роща</strong></a><br><strong style="font-size: 11pt;">(916)</strong>993-19-19</label></div>-->
<!-- Авиамоторная -->
                    <!--<div><span class="inz1" style="background-color: #FF0;"><input type="Radio" class="inz2" value="м. Новогиреево" name="adress" id="adr49"></span> <label for="adr37"><a href="javascript:;" onclick="window.open('/contacts/49.html')"><strong>м. Авиамоторная</strong></a><br><strong style="font-size: 11pt;">(926)</strong> 845-61-71</label></div>-->
<!-- конец блока -->
                    <div><span class="inz1" style="background-color: #FF0;"><input type="Radio" class="inz2" value="м. Деловой центр" name="adress" id="adr37"></span> <label for="adr37"><a href="javascript:;" onclick="window.open('/contacts/43.html')"><strong>м. Деловой центр</strong></a><br><strong style="font-size: 11pt;">(916)</strong> 232-80-30</label></div>
                    <div><span class="inz1" style="background-color: #FF0;"><input type="Radio" class="inz2" value="м. Новогиреево" name="adress" id="adr37"></span> <label for="adr37"><a href="javascript:;" onclick="window.open('/contacts/37.html')"><strong>м. Новогиреево</strong></a><br><strong style="font-size: 11pt;">(916)</strong> 232-80-30</label></div>
					<!--<div><span class="inz1" style="background-color: #ffab2e;"><input type="Radio" class="inz2" value="м. Академическая" name="adress" id="adr39"></span> <label for="adr39"><a href="javascript:;" onclick="window.open('/contacts/53.html')"><strong>м. Академическая</strong></a><br><strong style="font-size: 11pt;">(499)</strong> 724-50-02 </label></div>--> 
					<!--<div><span class="inz1" style="background-color: #ffab2e;"><input type="Radio" class="inz2" value="м. Алексеевская" name="adress" id="adr39"></span> <label for="adr39"><a href="javascript:;" onclick="window.open('/contacts/39.html')"><strong>м. Алексеевская</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 798-81-43</label></div> -->
					<div><span class="inz1" style="background-color: #ffab2e;"><input type="Radio" class="inz2" value="м. Бабушкинская" name="adress" id="adr16"></span> <label for="adr16"><a href="javascript:;" onclick="window.open('/contacts/16.html')"><strong>м. Бабушкинская</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 798-81-43</label></div>
					<div><span class="inz1" style="background-color: #ffab2e;"><input type="Radio" class="inz2" value="м. Новые черемушки" name="adress" id="adr10"></span> <label for="adr10"><a href="javascript:;" onclick="window.open('/contacts/10.html')"><strong>м. Новые черемушки</strong></a><br><strong style="font-size: 11pt;">(499)</strong> 724-50-02</label></div>
					<div><span class="inz1" style="background-color: #ffab2e;"><input type="Radio" class="inz2" value="м. Октябрьская" name="adress" id="adr11"></span> <label for="adr11"><a href="javascript:;" onclick="window.open('/contacts/11.html')"><strong>м. Октябрьская</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 988-14-14</label></div>
					<!--<div><span class="inz1" style="background-color: #ffab2e;"><input type="Radio" class="inz2" value="м. Третьяковская" name="adress" id="adr11"></span> <label for="adr11"><a href="javascript:;" onclick="window.open('/contacts/156.html')"><strong>м. Третьяковская</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 506-22-77</label></div>-->
				</div>
			</td>
			<td width="50%">
				<div id="list">
				
					<div><span class="inz1" style="background-color: #ff0000;"><input type="Radio" class="inz2" value="м. Комсомольская" name="adress" id="adr7"></span> <label for="adr7"><a href="javascript:;" onclick="window.open('/contacts/7.html')"><strong>м. Комсомольская</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 517-67-23</label></div>
					
					<div><span class="inz1" style="background-color: #ff0000;"><input type="Radio" class="inz2" value="м. Преображенская площадь" name="adress" id="adr30"></span> <label for="adr30"><a href="javascript:;" onclick="window.open('/contacts/30.html')"><strong>м. Преображенская площадь</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 763-77-89</label></div>
					<!--div><span class="inz1" style="background-color: #ff0000;"><input type="Radio" class="inz2" value="м. Спортивная" name="adress" id="adr15"></span> <label for="adr15"><a href="javascript:;" onclick="window.open('/contacts/54.html')"><strong>м. Спортивная</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 518-70-71</label></div>-->
					<div><span class="inz1" style="background-color: #ff0000;"><input type="Radio" class="inz2" value="м. Юго-Западная" name="adress" id="adr15"></span> <label for="adr15"><a href="javascript:;" onclick="window.open('/contacts/15.html')"><strong>м. Юго-Западная</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 518-70-71</label></div>
					<div><span class="inz1" style="background-color: #757575;"><input type="Radio" class="inz2" value="м. Алтуфьево" name="adress" id="adr23"></span> <label for="adr23"><a href="javascript:;" onclick="window.open('/contacts/23.html')"><strong>м. Алтуфьево</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 665-22-56</label></div>
					<!--<div><span class="inz1" style="background-color: #757575;"><input type="Radio" class="inz2" value="м. Нахимовский проспект" name="adress" id="adr23"></span> <label for="adr23"><a href="javascript:;" onclick="window.open('/contacts/52.html')"><strong>м. Нахимовский проспект</strong></a><br><strong style="font-size: 11pt;">(499)</strong> 724-50-02</label></div>-->
					<div><span class="inz1" style="background-color: #757575;"><input type="Radio" class="inz2" value="м. Пражская" name="adress" id="adr22"></span> <label for="adr22"><a href="javascript:;" onclick="window.open('/contacts/22.html')"><strong>м. Пражская</strong></a><br><strong style="font-size: 11pt;">(499)</strong> 391-97-27</label></div>
					<div><span class="inz1" style="background-color: #757575;"><input type="Radio" class="inz2" value="м. Дмитровская" name="adress" id="adr27"></span> <label for="adr27"><a href="javascript:;" onclick="window.open('/contacts/27.html')"><strong>м. Савеловская</strong></a><br><strong style="font-size: 11pt;">(916)</strong>  993-19-19</label></div>
					<!--<div><span class="inz1" style="background-color: #757575;"><input type="Radio" class="inz2" value="м. Пражская" name="adress" id="adr22"></span> <label for="adr22"><a href="javascript:;" onclick="window.open('/contacts/22.html')"><strong>м.Пражская</strong></a><br><strong style="font-size: 11pt;">(925)</strong> 706-18-44</label></div>
					<div><span class="inz1" style="background-color: #757575;"><input type="Radio" class="inz2" value="м. Тульская" name="adress" id="adr33"></span> <label for="adr33"><a href="javascript:;" onclick="window.open('/contacts/33.html')"><strong>м. Тульская</strong></a>,<br><strong style="font-size: 11pt;">(495)</strong> 988-14-14</label></div> -->
					<!--<div><span class="inz1" style="background-color: #757575;"><input type="Radio" class="inz2" value="м. Цветной бульвар" name="adress" id="adr9"></span> <label for="adr9"><a href="javascript:;" onclick="window.open('/contacts/9.html')"><strong>м. Цветной бульвар</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 545-48-42</label></div>-->
					<!--   <div><span class="inz1" style="background-color: #757575;"><input type="Radio" class="inz2" value="м. Южная" name="adress" id="adr24"></span> <label for="adr24"><a href="javascript:;" onclick="window.open('/contacts/24.html')"><strong>м. Южная</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 726-45-50</label></div> 
					<div><span class="inz1" style="background-color: #54a8ff;"><input type="Radio" class="inz2" value="м. Арбатская" name="adress" id="adr1"></span> <label for="adr1"><a href="javascript:;" onclick="window.open('/contacts/1.html')"><strong>м. Арбатская</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 545-48-42</label></div> -->
				  <!-- Пионерская-->
					<!--<div><span class="inz1" style="background-color: #54a8ff;"><input type="Radio" class="inz2" value="м. Пионерская" name="adress" id="adr48"></span> <label for="adr1"><a href="javascript:;" onclick="window.open('/contacts/48.html')"><strong>м. Пионерская</strong></a><br><strong style="font-size: 11pt;">(916)</strong> 500-75-83</label></div>-->
				  <!-- конец блока -->
					<!--<div><span class="inz1" style="background-color: #1f4b94;"><input type="Radio" class="inz2" value="м. Митино" name="adress" id="adr8"></span> <label for="adr8"><a href="javascript:;" onclick="window.open('/contacts/50.html')"><strong>м. Митино</strong></a><br><strong style="font-size: 11pt;">(901)</strong> 57-57-074</label></div>-->
					<div><span class="inz1" style="background-color: #1f4b94;"><input type="Radio" class="inz2" value="м. Молодёжная" name="adress" id="adr8"></span> <label for="adr8"><a href="javascript:;" onclick="window.open('/contacts/51.html')"><strong>м. Молодёжная</strong></a><br><strong style="font-size: 11pt;">(499)</strong> 714-68-28</label></div>
					<!--<div><span class="inz1" style="background-color: #1f4b94;"><input type="Radio" class="inz2" value="м. Щелковская" name="adress" id="adr29"></span> <label for="adr29"><a href="javascript:;" onclick="window.open('/contacts/29.html')"><strong>м. Щелковская</strong></a><br><strong style="font-size: 11pt;">(499)</strong> 748-11-82</label></div>	-->
					<div><span class="inz1" style="background-color: #1f4b94;"><input type="Radio" class="inz2" value="м. Электрозаводская" name="adress" id="adr14"></span> <label for="adr14"><a href="javascript:;" onclick="window.open('/contacts/14.html')"><strong>м. Электрозаводская</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 645-99-00</label></div>
				    <div><span class="inz1" style="background-color: #ebeaef;"><input type="Radio" class="inz2" value="Зеленоград" name="adress" id="adr20"></span> <label for="adr20"><a href="javascript:;" onclick="window.open('/contacts/20.html')"><strong>г. Зеленоград, г. Химки</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 664-37-18</label></div>
					<!--<div><span class="inz1" style="background-color: #ebeaef;"><input type="Radio" class="inz2" value="Красногорск" name="adress" id="adr17"></span> <label for="adr17"><a href="javascript:;" onclick="window.open('/contacts/17.html')"><strong>г. Красногорск</strong></a><br><strong style="font-size: 11pt;">(901)</strong> 575-70-74</label></div>-->
					<div><span class="inz1" style="background-color: #ebeaef;"><input type="Radio" class="inz2" value="Одинцово" name="adress" id="adr18"></span> <label for="adr18"><a href="javascript:;" onclick="window.open('/contacts/18.html')"><strong>г. Одинцово</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 973-5008</label></div>
					<div><span class="inz1" style="background-color: #ebeaef;"><input type="Radio" class="inz2" value="р-н Солцево" name="adress" id="adr40"></span> <label for="adr40"><a href="javascript:;" onclick="window.open('/contacts/40.html')"><strong>р-н Солнцево</strong></a><br><strong style="font-size: 11pt;">(495)</strong> 410-18-85</label></div>
					<div><span class="inz1" style="background-color: #ebeaef;"><input type="Radio" class="inz2" value="м. Румянцево" name="adress" id="adr47"></span> <label for="adr47"><a href="javascript:;" onclick="window.open('/contacts/47.html')"><strong>р-н Румянцево</strong></a><br><strong style="font-size: 11pt;">(925)</strong> 125-45-55</label></div>
				</div>
			</td>
		</tr>
	</tbody>
</table>
			